language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t fsamu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fsamu/docker-react npm run test